### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Unable to resume activity

### ISSUE THREAD

**Issue by SolaBe** [coomar2841/android-multipicker-library#8] opened 2016-03-10 21:13 UTC
I don't shure exactly, maybe it's problem in my code, but in method 
onActivityResult(int requestCode, int resultCode, Intent data)  data = null and application crash with exception
Fatal Exception: java.lang.RuntimeException
Unable to resume activity {com.olodroid.meme/com.olodroid.meme.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=68647, result=-1, data=Intent { act=com.htc.HTCAlbum.action.ITEM_PICKER_FROM_COLLECTIONS dat=content: typ=image/jpeg (has extras) }} to activity {com.olodroid.meme/com.olodroid.meme.MainActivity}: java.lang.NullPointerException

Full log:
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.olodroid.meme/com.olodroid.meme.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=68647, result=-1, data=Intent { act=com.htc.HTCAlbum.action.ITEM_PICKER_FROM_COLLECTIONS dat=content: typ=image/jpeg (has extras) }} to activity {com.olodroid.meme/com.olodroid.meme.MainActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3321)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3359)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2658)
       at android.app.ActivityThread.access$800(ActivityThread.java:156)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:157)
       at android.app.ActivityThread.main(ActivityThread.java:5872)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=68647, result=-1, data=Intent { act=com.htc.HTCAlbum.action.ITEM_PICKER_FROM_COLLECTIONS dat=content: typ=image/jpeg (has extras) }} to activity {com.olodroid.meme/com.olodroid.meme.MainActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3942)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3295)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3359)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2658)
       at android.app.ActivityThread.access$800(ActivityThread.java:156)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:157)
       at android.app.ActivityThread.main(ActivityThread.java:5872)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.NullPointerException
       at com.olodroid.meme.fragments.FragmentUserTemplate.onActivityResult(FragmentUserTemplate.java:184)
       at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:176)
       at android.app.Activity.dispatchActivityResult(Activity.java:5535)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3938)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3295)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3359)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2658)
       at android.app.ActivityThread.access$800(ActivityThread.java:156)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:157)
       at android.app.ActivityThread.main(ActivityThread.java:5872)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
       at dalvik.system.NativeStart.main(NativeStart.java) 

com.olodroid.meme.fragments.FragmentUserTemplate.onActivityResult(FragmentUserTemplate.java:184) 
in code
picker.submit(data);

**Comment by coomar2841** [comment] 2016-03-10 21:19
Looks like picker is null in `onActivityResult`. If it is null, you will need to create the object again. Please see the sample app for more details.

https://github.com/coomar2841/android-multipicker-library/blob/dev/app/src/main/java/com/kbeanie/multipicker/sample/ImagePickerActivity.java#L95

**Comment by coomar2841** [comment] 2016-05-13 09:22
Closing this. Please re-open if you still have a problem.

**Closed by coomar2841** 2016-05-13 09:22 UTC

**Comment by Isaacn123** [comment] 2017-11-18 01:27
Samsung Galaxy Grand Prime (fortunave3g), 1024MB RAM, Android 4.4
Report 1
java.lang.RuntimeException: 
 
  at android.app.ActivityThread.performDestroyActivity (ActivityThread.java:3651)
 
  at android.app.ActivityThread.handleDestroyActivity (ActivityThread.java:3669)
 
  at android.app.ActivityThread.access$1400 (ActivityThread.java:155)
 
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1296)
 
  at android.os.Handler.dispatchMessage (Handler.java:102)
 
  at android.os.Looper.loop (Looper.java:136)
 
  at android.app.ActivityThread.main (ActivityThread.java:5426)
 
  at java.lang.reflect.Method.invokeNative (Native Method)
 
  at java.lang.reflect.Method.invoke (Method.java:515)
 
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1268)
 
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1084)
 
  at dalvik.system.NativeStart.main (Native Method)
Caused by: java.lang.NullPointerException: 
 
  at io.ionic.keyboard.IonicKeyboard.onDestroy (IonicKeyboard.java:131)
 
  at org.apache.cordova.PluginManager.onDestroy (PluginManager.java:297)
 
  at org.apache.cordova.CordovaWebViewImpl.handleDestroy (CordovaWebViewImpl.java:480)
 
  at org.apache.cordova.CordovaActivity.onDestroy (CordovaActivity.java:315)
 
  at android.app.Activity.performDestroy (Activity.java:5468)
 
  at android.app.Instrumentation.callActivityOnDestroy (Instrumentation.java:1124)
 
  at android.app.ActivityThread.performDestroyActivity (ActivityThread.java:3638)

**Comment by Isaacn123** [comment] 2017-11-18 01:27
Help
