### ISSUE TITLE
Why do you copy videos?

### ISSUE THREAD

**Issue by Myeongwon-Kang** [coomar2841/android-multipicker-library#97] opened 2017-04-05 00:36 UTC
Why do you copy videos?
Because of this, it is slow to choose a big video.

**Comment by SanyasiraoM** [comment] 2017-04-11 04:38
@coomar2841 , Is there any chance for just to get paths of picked video or audio or image, instead of copying?

**Comment by Myeongwon-Kang** [comment] 2017-04-13 06:55
I only need video path.
Is there a way?

**Comment by DrewCarlson** [comment] 2017-04-13 14:58
@SanyasiraoM @Myeongwon-Kang https://github.com/coomar2841/android-multipicker-library/issues/29

**Comment by coomar2841** [comment] 2017-04-26 06:26
Duplicate of #70 and #29 . Closing this.

**Closed by coomar2841** 2017-04-26 06:26 UTC
